export const ERRORS = {
  'ACC001': 'Specified credentials is incorrect',
  'ACC002': 'Too much clients was found by query',
  'ACC003': 'Client with specified identifier not found',
  'ACC004': 'Client with specified email already exists',
  'ACC005': 'Client with specified phone number already exists',
  'ACC006': 'Client have to confirm email',
  'ACC007': 'Avatar of client not exist',
  'ACC008': 'Client need approve from back-office',
  'ATH001': 'Access denied for current client',
  'ATH002': 'Unauthorized request',
  'ATH003': 'Client is hidden and can’t be login in',
  'ATH004': 'Unknown confirmation token',
  'AUC001': 'Auction is finished already',
  'AUC002': 'Auction is not start yet',
  'BID001': 'Bid with specified identifier not found',
  'BID002': 'Error while checking conditions of changing tx status',
  'BID003': 'Error while withdrawal bid',
  'DIC001': 'Dictionary of questionnaires is empty',
  'DIC002': 'Questionnaire with specified id not found',
  'ERR001': 'Error is unknown',
  'ERR002': 'Invocation validation error',
  'ERR003': 'Unknown enumerate value',
  'ERR004': 'Http method not allowed',
  'ERR005': 'Error while convert data',
  'PRD001': 'Product with specified identifier not found',
  'PRD002': 'Error while checking conditions of changing product status',
  'PRD003': 'Photo of product not exist'
};
