package uk.co.afe.model.response;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.ToString;
import org.springframework.http.HttpStatus;
import uk.co.afe.model.ErrorCode;

/**
 * Technical response contains all information about error
 *
 * @author Sergey Teryoshin
 * 13.03.2018 17:17
 */
@ApiModel(description = "Technical response contains all information about error")
@Data
@ToString
public final class ErrorResponse {

    /**
     * An absolute URI that identifies the problem type.  When dereferenced,
     * it SHOULD provide human-readable documentation for the problem type
     * (e.g., using HTML).
     * <p> in our case just error code</p>
     *
     * @see ErrorCode
     */
    @ApiModelProperty("An absolute URI that identifies the problem type.  When dereferenced, " +
            "it SHOULD provide human-readable documentation for the problem type " +
            "(e.g., using HTML)." +
            "<p> in our case just error code</p>")
    private String type;

    /**
     * A short, summary of the problem type. Written in english and readable
     * for engineers (usually not suited for non technical stakeholders and
     * not localized); <p>example: Service Unavailable
     */
    @ApiModelProperty("A short, summary of the problem type. Written in english and readable " +
            "for engineers (usually not suited for non technical stakeholders and " +
            "not localized); <p>example: Service Unavailable")
    private String title;

    /**
     * A human readable explanation specific to this occurrence of the
     * problem.
     * <p>example: Connection to database timed out</p>
     */
    @ApiModelProperty("A human readable explanation specific to this occurrence of the " +
            "problem. " +
            "<p>example: Connection to database timed out</p>")
    private String detail;

    /**
     * The HTTP status code generated by the origin server for this occurrence
     * of the problem.
     * <p> example: 503</p>
     */
    @ApiModelProperty("The HTTP status code generated by the origin server for this occurrence " +
            "of the problem. " +
            "<p> example: 503</p>")
    private Integer status;

    /**
     * An absolute URI that identifies the specific occurrence of the problem.
     * It may or may not yield further information if dereferenced.
     */
    @ApiModelProperty("An absolute URI that identifies the specific occurrence of the problem. " +
            "It may or may not yield further information if dereferenced.")
    private Integer instance;

    public ErrorResponse(String type, String detail, HttpStatus status) {
        this.type = type;
        this.detail = detail;
        this.status = status.value();
        this.title = status.getReasonPhrase();
    }

}
