INSERT INTO tb_afe_platform (
    name, hidden
) VALUES
    ('Analysis Group', 0),
    ('Analysis Online', 0),
    ('Best Demo', 0),
    ('Best Test', 1),
    ('Best Test Online', 0),
    ('Demo Group', 0),
    ('Demo Online', 0),
    ('Exam Online', 0),
    ('Inspection Online', 0),
    ('Investigation', 0),
    ('My Analysis', 1),
    ('My Analysis Online', 0),
    ('My Demo Group', 0),
    ('My Demo Online', 0),
    ('My Exam', 0),
    ('My Exam Online', 0),
    ('My Inspection', 1),
    ('My Inspection Online', 0),
    ('My Test Group', 0),
    ('My Test Online', 0),
    ('My Trial', 1),
    ('My Trial Online', 0),
    ('The Analysis', 0),
    ('The Analysis Online', 0),
    ('The Demo Online', 0),
    ('The Exam', 0),
    ('The Test', 1),
    ('The Test Online', 0),
    ('Trial Online', 0);